[env:lilygo-t4]
board = lilygo-t4
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t4>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/lilygo-t4
	-DREDRAW_DELAY=1 # Used to improve navigation on menus for this device

	-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DDEVICE_NAME='"Lilygo T4 v1.3"'

	; This T4 ILI9341 panel renders correctly without color inversion,
	; unlike most Bruce panels which default to inverted.
	-DDEFAULT_COLOR_INVERTED=0

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

lib_ignore =
	${env_4mb.lib_ignore}
