; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:S3_supermini_madara]
board = S3_supermini_madara
build_src_filter =${env.build_src_filter} +<../boards/S3_supermini_madara>
board_build.arduino.memory_type = qio_qspi
board_build.partitions = custom_4Mb_full.csv
build_flags =
	${env.build_flags}
	-Iboards/S3_supermini_madara

	-DRF_TX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DRF_RX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DIR_TX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DIR_RX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	;Have buzzer
	-DBUZZ_PIN=47
	-D USE_HSPI_PORT=1
	-DDEVICE_NAME='"Madara Board"'


	-Os
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	# Restrict IR protocols to save Flash on 4mb devices
	-D_IR_ENABLE_DEFAULT_=false
	-DDECODE_HASH=true
	-DDECODE_NEC=true
	-DSEND_NEC=true
	-DDECODE_SAMSUNG=true
	-DSEND_SAMSUNG=true
	-DDECODE_RC5=true
	-DSEND_RC5=true
	-DDECODE_RC6=true
	-DSEND_RC6=true
	-DDECODE_LG=true
	-DSEND_LG=true
	-DDECODE_SONY=true
	-DSEND_SONY=true
	-DSEND_PANASONIC=true
	-DDECODE_PANASONIC=true
	-DSEND_RAW=true


lib_deps =
	    ${env.lib_deps}
